# Generated by Django 4.2.25 on 2025-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('total_loan_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_type', models.CharField(blank=True, choices=[('secured', 'Secured Loan'), ('unsecured', 'Unsecured Loan'), ('both', 'Both Secured & Unsecured')], max_length=20, null=True)),
                ('legal_notice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('preferred_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
